### ISSUE TITLE
Switch out Continuum Logo

### ISSUE THREAD

**Issue by amenity** [llvmpy/llvmpy#134]
Please update the Continuum Analytics logo on http://www.llvmpy.org/doc.html. 

![screen shot 2015-08-17 at 1 44 59 pm](https://cloud.githubusercontent.com/assets/1463708/9314484/da2fe992-44ee-11e5-9189-674c465a914f.png)

Assets available here: 
https://sites.google.com/a/continuum.io/wiki/marketing/public
(Click "Company Logos" to go here: https://drive.google.com/a/continuum.io/folderview?id=0B4LRrCKZqSrMfllwVmZibUJzc09DS0NqWEZ0VERKcnhyVlFIaHJFU043RGxjdW9MLVI3Wmc&usp=sharing) 

Let me know if you need further help/info.  Thank you!

**Comment by seibert** [comment]
Thanks!  As this project is deprecated, I've added a redirection to llvmlite and removed the Continuum logo.

**Comment by amenity** [comment]
Beautiful, gracias!

______________________________

_Amenity Applewhite_
_Creative Technologist_

[image: Continuum Analytics] http://continuum.io
