### ISSUE TITLE
Install on RPi3 issue with Quickstart

### ISSUE THREAD

**Issue by AcrimoniousMirth** [llvmpy/llvmpy#137]
Hi, sorry if this is the wrong place to contact but not sure where else. 
Installing on RPi3, downloaded llvm for ARMv7 (RPi returned that name) and unpacked it. I `cd`'d in and then tried the `./configure --enable-optimized --prefix=LLVM_INSTALL_PATH` (remembering to change the install path) and got back `bash: ./configure: No such file or directory`

**Comment by seibert** [comment]
llvmpy is no longer actively developed.  Are you looking for llvmlite?

**Comment by AcrimoniousMirth** [comment]
@seibert Thanks, odd to see it required by  pyntcloud alongside Numba, which wants llvmlite.
