### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by tan-wei** [llvmpy/llvmpy#139]
Seems not updated for a long time.

**Comment by seibert** [comment]
We moved our development effort to llvmlite several years ago: https://github.com/numba/llvmlite

Same goal (Python API for using LLVM), but with an easier to maintain implementation.  We do releases every 2 months or so, as it is a primary dependency of Numba.

**Comment by tan-wei** [comment]
Thanks!
Hope you have a good day.
